create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
create table comment (id bigint not null, content varchar(255), post_id bigint, primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table post (id bigint not null, content varchar(255), primary key (id))
create table post_comment (Post_id bigint not null, comments_id bigint not null)
alter table post_comment add constraint UK_se9l149iyyao6va95afioxsrl unique (comments_id)
alter table comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post (id)
alter table post_comment add constraint FKagqftk08s8sjuc6bbr9v99vbe foreign key (comments_id) references comment (id)
alter table post_comment add constraint FKnm3lpb10fjje1itg5x6c7w7w4 foreign key (Post_id) references post (id)
